version: 2
jobs:
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Unit Test
          command: echo true
  build_and_publish:
    docker:
      - image: google/cloud-sdk
    environment:
      - GOOGLE_PROJECT_ID: "document-automation-dev"
      - GOOGLE_STORAGE_BUCKET_URL: "gs://107906084271_fuzzylabs_document-automation_dev_cloud-functions"
    steps:
      - checkout
      - run:
          name: Create Cloud Function Classify Zip File
          command: |
            apt-get install -qq -y zip
            pushd functions/classify && zip -r classify.zip . && popd
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Push content to bucket
          command: gsutil -m cp functions/classify/classify.zip ${GOOGLE_STORAGE_BUCKET_URL}
  deploy_to_dev:
    docker:
      - image: hashicorp/terraform:0.12.5
    environment:
      - ENV: "dev"
      - REGION: "europe-west1"
      - TERRAGRUNT_VERSION: "0.19.9"
    steps:
      - checkout
      - run:
          name: Install Terragrunt
          command: |
            apk add -q curl
            curl -sL https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_386 -o /bin/terragrunt
            chmod +x /bin/terragrunt
      - run:
          name: Terragrunt Plan
          command: |
            cd terraform/dev/europe-west1/services/cloud_functions
            terragrunt plan

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build_and_publish:
          requires:
            - test
          #filters:
          #  branches:
          #    only:
          #      - master
      - deploy_to_dev:
          #type: approval
          requires:
            - build_and_publish
          #filters:
          #  branches:
          #    only:
          #      - master
