version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    environment:
      - GOOGLE_PROJECT_ID: "document-automation-dev"
      - GOOGLE_STORAGE_BUCKET_URL: "gs://TODO-FIXME"
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Create Cloud Function Classifier Zip File
          command: pushd functions/classifier && zip classifier.zip . && popd
      - run:
          name: Push content to bucket
          command: gsutil -m cp functions/classifier/classifier.zip ${GOOGLE_STORAGE_BUCKET_URL}
